import { useState } from "react";

const projects = [
  { title: "Anonymous Chat App", period: "2024 — ongoing", description: "A real-time anonymous communication app built around the simple idea that a conversation should be easy to start. Users can make public or private rooms, share a key, and talk without signing up.", detail: "Node.js · Express · Socket.IO · Supabase", role: "Product thinking, backend, interface, deployment", link: "https://github.com/kekeli101/anonymous-chat-app" },
  { title: "Tekmart", period: "student marketplace", description: "A marketplace concept for university students — a practical answer to the “does anyone have one of these?” messages that fill campus group chats.", detail: "Product structure · web development · student needs", role: "Exploring the next useful version" },
  { title: "Restaurant Ordering System", period: "operations / ordering", description: "A platform that connects customer ordering, kitchen management, administration, and Telegram notifications in one flow. The interesting part was keeping everyone’s version of the order in sync.", detail: "customer ordering · kitchen view · admin · Telegram alerts", role: "Built as a systems exercise" },
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
function ArrowLink({ children, href = "#" }: { children: React.ReactNode; href?: string }) { return <a className="arrow-link" href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>{children} <span>↗</span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [photo, setPhoto] = useState<string | null>(null);
  const closeMenu = () => setMenuOpen(false);

  return <div className="portfolio-shell">
    <header className="site-header"><a className="wordmark" href="#top"><span className="wordmark-mark">K</span><span>Owusu Kekeli Prince</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="site-nav">{menuOpen ? "Close" : "Menu"} <span>↘</span></button><nav id="site-nav" className={`site-nav ${menuOpen ? "open" : ""}`} aria-label="Main navigation"><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#journey" onClick={closeMenu}>Journey</a><a href="#photography" onClick={closeMenu}>Photography</a><a href="#contact" onClick={closeMenu}>Contact</a></nav></header>
    <main id="top">
      <section className="hero section-wrap"><div className="hero-kicker"><Eyebrow>01 / hello</Eyebrow><span className="availability"><i /> open to interesting work</span></div><div className="hero-grid"><h1>Hey, I’m <em>Kekeli.</em></h1><div className="hero-intro"><p className="lede">Computer engineering student at KNUST, developer, researcher, and photographer. I like building useful things, figuring out how systems work, and occasionally carrying a camera around.</p><div className="hero-links"><ArrowLink href="#work">See the work</ArrowLink><a className="text-link" href="#about">A little more about me</a><a className="text-link" href="/assets/owusu-prince-cv.pdf" download>Download my CV ↓</a></div></div></div><div className="hero-footer"><span>Kumasi, Ghana</span><span>Currently learning: systems &amp; embedded things</span><span className="scroll-note">Scroll to explore ↓</span></div></section>
      <section className="currently section-wrap"><div><Eyebrow>Right now</Eyebrow><h2>Finishing my Computer Engineering degree at KNUST, working on piezoelectric energy harvesting, and getting more serious about embedded systems and data.</h2></div><div className="currently-meta"><span>Expected graduation</span><strong>September 2026</strong><span>Also in the mix</span><strong>Photography · research · Zindi</strong></div></section>
      <section id="work" className="work section-wrap"><div className="section-heading"><Eyebrow>02 / selected work</Eyebrow><h2>Things I’ve made<br /><em>and learned from.</em></h2><p className="section-note">A small collection of software and engineering projects. I’m more interested in the decisions behind them than a long list of technologies.</p></div>
        <article className="project project-featured"><div className="project-image project-real-image"><img src="/assets/anonymous-chat-room.png" alt="Anonymous Chat App room interface" /><span className="image-caption">01 — a real room, not a concept mockup</span></div><div className="project-copy"><div className="project-label"><span>Project 01</span><span>{projects[0].period}</span></div><h3>{projects[0].title}</h3><p>{projects[0].description}</p><dl className="project-details"><div><dt>Built with</dt><dd>{projects[0].detail}</dd></div><div><dt>My role</dt><dd>{projects[0].role}</dd></div></dl><ArrowLink href={projects[0].link}>View the repository</ArrowLink></div></article>
        <article className="project project-split"><div className="project-copy"><div className="project-label"><span>Project 02</span><span>{projects[1].period}</span></div><h3>{projects[1].title}</h3><p>{projects[1].description}</p><dl className="project-details"><div><dt>Focus</dt><dd>{projects[1].detail}</dd></div><div><dt>Status</dt><dd>{projects[1].role}</dd></div></dl><span className="quiet-note">Case study in progress</span></div><div className="project-image project-image-market"><div className="market-top"><span>tekmart</span><i>⌕</i></div><div className="market-row"><b>Find it nearby.</b><span>sell something →</span></div><div className="market-items"><span>laptop / GHS 3,200</span><span>desk lamp / GHS 120</span><span>textbooks / GHS 80</span></div><span className="image-caption">02 — a product direction, honestly marked</span></div></article>
        <article className="project project-wide"><div className="wide-number">03</div><div><div className="project-label"><span>Project 03</span><span>{projects[2].period}</span></div><h3>{projects[2].title}</h3><p>{projects[2].description}</p><div className="tag-line">{projects[2].detail.split(" · ").map((tag) => <span key={tag}>{tag}</span>)}</div></div><span className="quiet-note">{projects[2].role}</span></article>
      </section>
      <section id="photography" className="photography section-wrap"><div className="photo-intro"><div><Eyebrow>03 / off the screen</Eyebrow><h2>Photography<br /><em>by Kels.</em></h2></div><div className="photo-description"><p>Photography is how I slow down. I’ve covered campus, church, and community events, and I’m slowly building an archive of the moments worth keeping.</p><ArrowLink href="#contact">Ask about a shoot</ArrowLink></div></div><div className="photo-grid" aria-label="Photography archive">{[["Portraits", "/assets/kekeli-portrait.jpg"], ["Campus life", "/assets/kekeli-field.jpg"], ["Everyday moments", "/assets/kekeli-portrait.jpg"]].map(([name, src], i) => <button key={name} className={`photo-tile photo-tile-${i === 0 ? "tall" : i === 1 ? "wide" : "small"}`} onClick={() => setPhoto(name)}><img src={src} alt={`${name} photograph by Kekeli`} /><span className="photo-placeholder-mark">+</span><span className="photo-tile-label">{name}<small>view larger</small></span></button>)}</div></section>
      <section id="about" className="about section-wrap"><div className="section-heading"><Eyebrow>04 / a bit about me</Eyebrow><h2>Curious about<br /><em>the whole stack.</em></h2></div><div className="about-grid"><div className="about-copy"><img className="about-portrait" src="/assets/kekeli-field.jpg" alt="Kekeli in an orange KNUST engineering jacket" /><p className="large-copy">I’m a Computer Engineering student at KNUST, learning by making things. Some days that means writing software; other days it means getting a microcontroller to behave, or wondering why a circuit is doing something it absolutely should not.</p><p>I’ve worked with the Electricity Company of Ghana, led research projects with MSSAATECH USA, and built small products that sit between software, data, and real-world systems.</p><p>Outside of coursework, I photograph campus, church, and community events. I also served as Vice President of Computer Engineering at KNUST and led Team Titans to a second-place finish at the Heidelberg Materials Digital Hub Hackathon.</p></div><div className="skills-list">{[["Languages", "Python · JavaScript · HTML · CSS · C · C++"], ["Software", "Django · Flask · React · Firebase · PostgreSQL"], ["AI & data", "Machine Learning · Power BI · Tableau · Pandas · NumPy"], ["Networking", "Cisco Networking · TCP/IP · troubleshooting"], ["Engineering", "Embedded systems · DSP · system design · PCB/circuits"]].map(([name, value]) => <div key={name}><span>{name}</span><p>{value}</p></div>)}</div></div></section>
      <section id="journey" className="journey section-wrap"><div className="section-heading"><Eyebrow>05 / the road so far</Eyebrow><h2>Work, research,<br /><em>and responsibility.</em></h2><p className="section-note">The parts of the journey that shaped how I approach problems and people.</p></div><div className="timeline"><div className="timeline-item"><span>2025</span><div><h3>ECG · IT &amp; engineering intern</h3><p>Supported computer systems, transformer inspections, substation maintenance, and multidisciplinary project work at the Accra East Regional Office.</p></div></div><div className="timeline-item"><span>2024 — 2026</span><div><h3>MSSAATECH USA · lead researcher</h3><p>Led international technology research projects, coordinating planning, documentation, technical execution, and collaboration.</p></div></div><div className="timeline-item"><span>2024 — 2025</span><div><h3>KNUST · vice president, computer engineering</h3><p>Represented students and worked with faculty and student leaders to coordinate academic, professional, and community initiatives.</p></div></div><div className="timeline-item"><span>Tweek 2025</span><div><h3>Heidelberg Materials Digital Hub Hackathon · 2nd place</h3><p>Led Team Titans through the competition as team leader.</p></div></div></div></section>
      <section id="contact" className="contact section-wrap"><div><Eyebrow>06 / say hello</Eyebrow><h2>Have something<br /><em>interesting to build?</em></h2></div><div className="contact-links"><p>I’m available for thoughtful software, research, data, embedded systems, and photography collaborations.</p><a className="contact-email" href="mailto:owusukekeliprince@gmail.com">owusukekeliprince@gmail.com <span>↗</span></a><div className="social-links"><a href="https://github.com/kekeli101" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/owusu-kekeli-prince-973871299" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://www.zindi.africa" target="_blank" rel="noreferrer">Zindi ↗</a><a href="#photography">Shot by Kels ↘</a></div><a className="cv-link" href="/assets/owusu-prince-cv.pdf" download>Download CV <small>PDF · updated September 2026</small> ↓</a></div></section>
    </main>
    <footer className="site-footer section-wrap"><span>© 2026 Owusu Kekeli Prince</span><span>Made with attention, not a template.</span><a href="#top">Back to top ↑</a></footer>
    {photo && <div className="photo-modal" role="dialog" aria-modal="true" onClick={(event) => event.target === event.currentTarget && setPhoto(null)}><div className="modal-inner"><button className="modal-close" onClick={() => setPhoto(null)} aria-label="Close">×</button><Eyebrow>photography archive</Eyebrow><h2>{photo} — coming soon.</h2><p>The actual photographs will live here once the archive is ready. No filler images — promise.</p></div></div>}
  </div>;
}
