import { useState } from "react";

const projects = [
  { number: "01", title: "Anonymous Chat App", period: "2024 — ongoing", description: "A real-time anonymous communication app built around the simple idea that a conversation should be easy to start. Users can make public or private rooms, share a key, and talk without signing up.", detail: "Node.js · Express · Socket.IO · Supabase", role: "Product thinking, backend, interface, deployment", link: "https://github.com/kekeli101/anonymous-chat-app", visual: "chat" },
  { number: "02", title: "Tekmart", period: "student marketplace", description: "A marketplace concept for university students — a practical answer to the “does anyone have one of these?” messages that fill campus group chats.", detail: "Product structure · web development · student needs", role: "Exploring the next useful version", visual: "market" },
  { number: "03", title: "Restaurant Ordering System", period: "operations / ordering", description: "A platform that connects customer ordering, kitchen management, administration, and Telegram notifications in one flow. The interesting part was keeping everyone’s version of the order in sync.", detail: "customer ordering · kitchen view · admin · Telegram alerts", role: "Built as a systems exercise", visual: "wide" },
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
function ArrowLink({ children, href = "#" }: { children: React.ReactNode; href?: string }) { return <a className="arrow-link" href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>{children} <span>↗</span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [photo, setPhoto] = useState<string | null>(null);
  const closeMenu = () => setMenuOpen(false);

  return <div className="portfolio-shell">
    <header className="site-header">
      <a className="wordmark" href="#top"><span className="wordmark-mark">K</span><span>kekeli.dev</span></a>
      <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="site-nav">{menuOpen ? "Close" : "Menu"} <span>↘</span></button>
      <nav id="site-nav" className={`site-nav ${menuOpen ? "open" : ""}`} aria-label="Main navigation">
        <a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#photography" onClick={closeMenu}>Photography</a><a href="#contact" onClick={closeMenu}>Contact</a>
      </nav>
    </header>

    <main id="top">
      <section className="hero section-wrap"><div className="hero-kicker"><Eyebrow>01 / hello</Eyebrow><span className="availability"><i /> open to interesting work</span></div><div className="hero-grid"><h1>Hey, I’m <em>Kekeli.</em></h1><div className="hero-intro"><p className="lede">Computer engineering student, developer, and photographer. I like building useful things, figuring out how systems work, and occasionally carrying a camera around.</p><div className="hero-links"><ArrowLink href="#work">See the work</ArrowLink><a className="text-link" href="#about">A little more about me</a></div></div></div><div className="hero-footer"><span>Accra, Ghana</span><span>Currently learning: systems &amp; embedded things</span><span className="scroll-note">Scroll to explore ↓</span></div></section>

      <section id="work" className="work section-wrap"><div className="section-heading"><Eyebrow>02 / selected work</Eyebrow><h2>Things I’ve made<br /><em>and learned from.</em></h2><p className="section-note">A small collection of software and engineering projects. I’m more interested in the decisions behind them than a long list of technologies.</p></div>
        <article className="project project-featured"><div className="project-image project-image-chat"><div className="browser-bar"><span /><span /><span /><b>anonymous-chat-app</b></div><div className="chat-preview"><div className="chat-line short" /><div className="chat-line" /><div className="chat-line long" /><div className="chat-line own" /><div className="chat-line own short" /></div><span className="image-caption">01 — realtime room, viewed from the inside</span></div><div className="project-copy"><div className="project-label"><span>Project 01</span><span>2024 — ongoing</span></div><h3>Anonymous Chat App</h3><p>{projects[0].description}</p><dl className="project-details"><div><dt>Built with</dt><dd>{projects[0].detail}</dd></div><div><dt>My role</dt><dd>{projects[0].role}</dd></div></dl><ArrowLink href={projects[0].link}>View on GitHub</ArrowLink></div></article>
        <article className="project project-split"><div className="project-copy"><div className="project-label"><span>Project 02</span><span>student marketplace</span></div><h3>Tekmart</h3><p>{projects[1].description}</p><dl className="project-details"><div><dt>Focus</dt><dd>{projects[1].detail}</dd></div><div><dt>Status</dt><dd>{projects[1].role}</dd></div></dl><span className="quiet-note">Case study in progress</span></div><div className="project-image project-image-market"><div className="market-top"><span>tekmart</span><i>⌕</i></div><div className="market-row"><b>Find it nearby.</b><span>sell something →</span></div><div className="market-items"><span>laptop / GHS 3,200</span><span>desk lamp / GHS 120</span><span>textbooks / GHS 80</span></div><span className="image-caption">02 — a market made for campus life</span></div></article>
        <article className="project project-wide"><div className="wide-number">03</div><div><div className="project-label"><span>Project 03</span><span>operations / ordering</span></div><h3>Restaurant Ordering System</h3><p>{projects[2].description}</p><div className="tag-line">{projects[2].detail.split(" · ").map((tag) => <span key={tag}>{tag}</span>)}</div></div><span className="quiet-note">{projects[2].role}</span></article>
      </section>

      <section id="photography" className="photography section-wrap"><div className="photo-intro"><div><Eyebrow>03 / off the screen</Eyebrow><h2>Photography<br /><em>by Kels.</em></h2></div><div className="photo-description"><p>Photography is how I slow down. I’m still building this archive — portraits, street corners, events, and the ordinary details that usually pass by.</p><ArrowLink href="#contact">Ask about a shoot</ArrowLink></div></div><div className="photo-grid" aria-label="Photography archive placeholders">{["Portraits", "Street", "Everyday moments"].map((name, i) => <button key={name} className={`photo-tile photo-tile-${i === 0 ? "tall" : i === 1 ? "wide" : "small"}`} onClick={() => setPhoto(name)}><span className="photo-placeholder-mark">+</span><span className="photo-tile-label">{name}<small>archive coming soon</small></span></button>)}</div></section>

      <section id="about" className="about section-wrap"><div className="section-heading"><Eyebrow>04 / a bit about me</Eyebrow><h2>Curious about<br /><em>the whole stack.</em></h2></div><div className="about-grid"><div className="about-copy"><p className="large-copy">I’m studying computer engineering and learning by making things. Some days that means writing software; other days it means getting a microcontroller to behave, or wondering why a circuit is doing something it absolutely should not.</p><p>Outside of coursework, I’ve been working on small products, real-time apps, and the occasional photo story. I like the part where a vague idea becomes something another person can actually use.</p><p>This site is intentionally a work in progress — much like the person it belongs to.</p></div><div className="skills-list">{[["Languages", "Python · JavaScript · HTML · CSS"], ["Backend", "Node.js · Express · Django · Flask"], ["Data & tools", "PostgreSQL · Firebase · Git · GitHub"], ["Engineering", "Embedded systems · Microcontrollers · Digital systems"]].map(([name, value]) => <div key={name}><span>{name}</span><p>{value}</p></div>)}</div></div></section>

      <section id="contact" className="contact section-wrap"><div><Eyebrow>05 / say hello</Eyebrow><h2>Have something<br /><em>interesting to build?</em></h2></div><div className="contact-links"><p>I’m always up for a good problem, a thoughtful collaboration, or a conversation about cameras and code.</p><a className="contact-email" href="mailto:hello@kekeli.dev">hello@kekeli.dev <span>↗</span></a><div className="social-links"><a href="https://github.com/kekeli101" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/owusu-kekeli-prince-973871299" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="#photography">Shot by Kels ↘</a></div></div></section>
    </main>
    <footer className="site-footer section-wrap"><span>© 2026 Kekeli</span><span>Made with attention, not a template.</span><a href="#top">Back to top ↑</a></footer>
    {photo && <div className="photo-modal" role="dialog" aria-modal="true" onClick={(event) => event.target === event.currentTarget && setPhoto(null)}><div className="modal-inner"><button className="modal-close" onClick={() => setPhoto(null)} aria-label="Close">×</button><Eyebrow>photography archive</Eyebrow><h2>{photo} — coming soon.</h2><p>The actual photographs will live here once the archive is ready. No filler images — promise.</p></div></div>}
  </div>;
}
